#if !canImport(ObjectiveC)
import XCTest

extension Float32DegreeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Float32DegreeTests = [
        ("testDegree", testDegree),
        ("testRadian", testRadian),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Float32DegreeTests.__allTests__Float32DegreeTests),
    ]
}
#endif
