#if !canImport(ObjectiveC)
import XCTest

extension FloatingPointDegreeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FloatingPointDegreeTests = [
        ("testDegree", testDegree),
        ("testRadian", testRadian),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FloatingPointDegreeTests.__allTests__FloatingPointDegreeTests),
    ]
}
#endif
